# Generated by Django 4.1 on 2022-09-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airpollution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollutantentry',
            name='country',
        ),
    ]
