# Generated by Django 4.1 on 2022-09-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpollution', '0004_pollutantentry_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollutantentry',
            name='pollution_level',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
