# Generated by Django 4.1 on 2022-09-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpollution', '0005_alter_pollutantentry_pollution_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollutantentry',
            name='pollution_level',
            field=models.FloatField(),
        ),
    ]
