# Generated by Django 4.1 on 2022-09-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpollution', '0006_alter_pollutantentry_pollution_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='color',
            field=models.CharField(default='#000000', max_length=10),
        ),
        migrations.AddField(
            model_name='pollutant',
            name='color',
            field=models.CharField(default='#000000', max_length=10),
        ),
        migrations.AddField(
            model_name='pollutant',
            name='limit_value',
            field=models.SmallIntegerField(null=True),
        ),
    ]
