# Generated by Django 4.1 on 2022-09-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_myapp_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='myapp',
            name='url',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
